### PR TITLE
Automation of npm/yarn installation

### PR DESCRIPTION
**Pull request by anuveyatsu**
This PR for automation of the CLI tool testing when it's installed via NPM or yarn:

- refactored `.travis.yaml` so it uses Linux and MacOS with node versions 7, 8 and 9 to test the CLI tool
  - it only runs after deployment and doesn't run regular tests
- added `test-script.sh` shell script for handling all those tests

### CODE REVIEW

**Review by AcckiyGerman — APPROVED** [review]
I'm not used to Travis config, but `test-script.sh` looks GOOD for me, with `-ev` option it will fail if any error.

Actually here are more tests than we need to check it is installable :)

**Comment by anuveyatsu** [comment]
@AcckiyGerman yes, the idea is that this is a starting point and we can extend those tests in the shell script in the future.

**Review by Mikanebu — APPROVED** [review]
Looks good

**Comment by AcckiyGerman** [comment]
@anuveyatsu .... mmm then it is not good.
I was working in the CloudLinux and we have hundreds of BASH tests, like we will have (>100 tests in the QA spreadsheet)

At first they put all the tests in one `.sh` file, it was HUGE and our test-file will be HUGE as well. It is  hard to find which test was failed, hard to fix the tests itself etc...

Then we split this tests into separate bash files and create a script which run them one by one, catching errors. There then was problems to maintain the same test format, help lib for unify the tests, etc...

At the end they give up supporting all that and ended up with `bats shell test framework` to handle all shell tests.

I think we can use their experience to avoid all this problems :)
Take a look on https://github.com/sstephenson/bats please, I think we could use it as well.

**Comment by anuveyatsu** [comment]
@AcckiyGerman great! As we've already discussed lets have only basic CLI command tests in this shell script for now.

**Pull request merged**
